/**
 * Created by srivaspa on 22/04/18.
 */
export const LOAD_MOVIE_SUCESS = "LOAD_MOVIE_SUCESS";
export const LOAD_ALLMOVIE_SUCESS = "LOAD_ALLMOVIE_SUCESS";
export const LOAD_MOVIE_DETAIL_SUCESS = "LOAD_MOVIE_DETAIL_SUCESS";